README
Upplysingaverkfraedi/capstone-the-north pull request #10
Opened 2024-11-17 22:30 UTC by gigjamarin

Ég er búin að uppfæra README með öllum helstu upplýsingum varðandi uppsetningu gagnagrunns. Let me know ef þið sjáið eitthað sem þarf að laga

2024-11-18 17:41 UTC, asdisgudmunds commented on README.md
> +python3 code/genres.py
Sýnist vanta þennan kóða inn í code

2024-11-18 19:02 UTC, asdisgudmunds requested changes
Geggjað, nokkur comment annars virkaði mjög vel að fylgja þessum leiðbeiningum til að búa til gagnagrunninn og fá mælaborðið (sem á reyndar eftir að koma inn á git núna) til að virka. 
Kannski eftir að setja inn sql töflurnar í databaseið í gröfunum með leikstjórana frá Ásdísi H

2024-11-18 19:02 UTC, asdisgudmunds commented on README.md
Þurfti að keyra Get-Content code/create_db2.sql | sqlite3 data/rotten_tomatoes.db
Því hitt virkaði ekki hjá mér

2024-11-18 19:02 UTC, asdisgudmunds commented on README.md
> +Síðan þarf að bæta við dálkinum movie_id í töfluna okkar. Það er einfaldlega dálkur sem gefur hverri kvikmynd id númer sem hægt er að nýta seinna meir til að gera fleiri töflur. Það eru nokkrar leiði
Myndi ekki skrifa "ég gerði þetta"

2024-11-18 19:02 UTC, asdisgudmunds commented on README.md
> +Forritið sem við notum heitir `createactors_info` og er að finna í code möppunni. Búið er til töfluna með því að keyra skipunina:
Cinemagoer er eitthvað skrítið hjá mér þannig virkaði ekki nema með  því að gera python en ekki python3 af einhverjum ástæðum.

2024-11-18 19:02 UTC, asdisgudmunds commented on README.md
> -## Nauðsynleg bókasöfn
Myndi hafa þetta ofar eða allavega vitna í þetta ofar

2024-11-18 19:02 UTC, asdisgudmunds commented on README.md
> +python3 code/get_biography.py
Tölvan mín kannski aftur eitthvað skrítin með python og python3 (þó ég sjái á vscode að ég sé að nota útgáfu 3 af python) því það virkaði bara að gera python. Gætum haft eitthvað svona mögulegan villukafla neðst þar sem geta verið einhverjar lausnir.

2024-11-18 19:02 UTC, asdisgudmunds commented on README.md
> +python3 code/actors_in_info.py
Fæ þennan error um að processed sé ekki til sem dálkur:  line 68, in <module>
    cursor.execute(f"""
sqlite3.OperationalError: table main_actors_in_info has no column named processed 

gat lagað það með því að bæta við í actors_in_info.py 

processed  -- Include the processed column

í þessum hluta: cursor.execute("""
    CREATE TABLE main_actors_in_info AS
    SELECT
        rotten_tomatoes_link,
        NULL AS actor_in_info,  -- New column for individual actor
        movie_title,
        movie_info,
        critics_consensus,
        content_rating,
        genres,
        directors,
        authors,
        original_release_date,
        streaming_release_date,
        runtime,
        production_company,
        tomatometer_status,
        tomatometer_rating,
        tomatometer_count,
        audience_status,
        audience_rating,
        audience_count,
        tomatometer_top_critics_count,
        tomatometer_fresh_critics_count,
        tomatometer_rotten_critics_count,
        movie_id,
        actors,  -- Keep the original actors column
        processed  -- Include the processed column
    FROM rotten_tomatoes_movies_dicaprio_winslet WHERE 0
""")

2024-11-18 19:22 UTC, gigjamarin commented on README.md
Aaa, sýnist það vera því þú ert í Windows tölvu þessi skipun virkar ekki í mac, en ég skal laga

2024-11-18 23:38 UTC, asdishalla approved these changes
Mér finnst þetta mjög flott og lýsir öllu ferlinu við gerð þessa verkefnis mjög vel. Ég sé engar villur og held það þurfi ekki að bæta neinu við þetta

2024-11-19 00:42 UTC, gudnylilja approved these changes

2024-11-19 00:48 UTC, asdishalla approved these changes
Flott

2024-11-19 00:51 UTC, asdisgudmunds commented
ennþa stafsetningavillan sme þu varst að laga á að vera capstone_docs

2024-11-19 01:18 UTC, gigjamarin commented
búin að laga stafsetningavilluna

2024-11-19 01:21 UTC, asdisgudmunds approved these changes
Geggjað

2024-11-19 01:25 UTC, merged